[package]
name = "tinyusb-types"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Core USB 2.0/3.0 & PD types, descriptors, setup packets, and standard requests (no_std)"

[dependencies]
byteorder = { workspace = true }
bitflags = { workspace = true }

[features]
default = []
